apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
data:
  postgresql-password: "V2JyVHBOM2c3cQ=="
  repmgr-password: "Y0c5emRHZHlaWE5BTVRJeg=="
  admin-password: "Y0c5emRHZHlaWE5BTVRJeg=="
